name: Cypress Cucumber Tests

on:
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cypress run with report
        run: npm run test:with-report

      - name: Print working directory
        run: pwd

      - name: Rename report file
        run: mv cypress/reports/report.html cypress/reports/index.html

      - name: Upload reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports/
          if-no-files-found: ignore
          retention-days: 2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports
          publish_branch: gh-pages
